[package]
name = "doomfire"
version = "0.1.0"
authors = ["fi3ry_d3v3l0per"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["winuser"] }

[dependencies]
rand = "0.5.1"

